### PR TITLE
Allow for the meta_description field to be parsed

### PR DESCRIPTION
**Pull request by jsblair9**
Just a config update on the blueprint to include `'antlers' => true,` will allow the field to be parsed making it super easy to set a field from the entry

### CODE REVIEW

**Comment by AndrewHaine** [comment]
Hey @jsblair9 ,

Thanks for this, good shout and I've just had a quick test my end - this looks all good and works well. Just one request; please could `antlers` be added to the `twitter_description` fields too (just to keep things consistent), then I'll get this released :) 

Cheers,
Andrew

**Comment by jsblair9** [comment]
@AndrewHaine ah yeah of course! my bad... coming right up

**Comment by jsblair9** [comment]
ok added it to both places... 

Also, in the future adding it to the `schema_objects` may be helpful -- I've needed it in a v2 project. But don't want any potential pitfalls to hold this part up since it is straight forward 

Thanks!

**Comment by AndrewHaine** [comment]
Sweet, thank you @jsblair9 ,

That's a very good point, I'll open an issue about antlers in `schema_objects`. For in-house projects I tend to opt for writing custom tags for page-specific schema, especially now we're using graphs, but agreed that allowing antlers in the field would be a quick win but might require a bit of testing our end.

Thanks,
Andrew

**Pull request merged**
